/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ChartData, ChartOptions } from "chart.js";
export { ChartData, ChartOptions } from "chart.js";
export namespace Components {
    interface TheChart {
        /**
          * Accessibility label for the canvas image.
         */
        "canvasAriaLabel": string;
        /**
          * Cart.js data parameter, contains labels, datasets...
         */
        "chartData": ChartData<'bar'>;
        /**
          * Approximate height of the chart for initial rendering and for maintaining aspect ratio.
         */
        "chartHeight": number;
        /**
          * Cart.js options for the Bar chart.
         */
        "chartOptions": ChartOptions<'bar'>;
        /**
          * Approximate width of the chart for initial rendering and for maintaining aspect ratio.
         */
        "chartWidth": number;
    }
}
declare global {
    interface HTMLTheChartElement extends Components.TheChart, HTMLStencilElement {
    }
    var HTMLTheChartElement: {
        prototype: HTMLTheChartElement;
        new (): HTMLTheChartElement;
    };
    interface HTMLElementTagNameMap {
        "the-chart": HTMLTheChartElement;
    }
}
declare namespace LocalJSX {
    interface TheChart {
        /**
          * Accessibility label for the canvas image.
         */
        "canvasAriaLabel"?: string;
        /**
          * Cart.js data parameter, contains labels, datasets...
         */
        "chartData"?: ChartData<'bar'>;
        /**
          * Approximate height of the chart for initial rendering and for maintaining aspect ratio.
         */
        "chartHeight"?: number;
        /**
          * Cart.js options for the Bar chart.
         */
        "chartOptions"?: ChartOptions<'bar'>;
        /**
          * Approximate width of the chart for initial rendering and for maintaining aspect ratio.
         */
        "chartWidth"?: number;
    }
    interface IntrinsicElements {
        "the-chart": TheChart;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "the-chart": LocalJSX.TheChart & JSXBase.HTMLAttributes<HTMLTheChartElement>;
        }
    }
}
